### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by avrahamswissa** [ssrikanta/pytest-excel#23]
Hi there,
While trying to install pytest-excel on **Ubuntu 14.04 or 16.04**, with **Python 2.7** installed, I get the following error:

 ```
   ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-Wb2xSQ/pytest-excel/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Wb2xSQ/pytest-excel/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-o5VQRA
         cwd: /tmp/pip-install-Wb2xSQ/pytest-excel/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Wb2xSQ/pytest-excel/setup.py", line 22, in <module>
        version=get_version('version.txt'),
      File "/tmp/pip-install-Wb2xSQ/pytest-excel/setup.py", line 11, in get_version
        f = open(os.path.join(here, filename))
    IOError: [Errno 2] No such file or directory: '/tmp/pip-install-Wb2xSQ/pytest-excel/version.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**setuptools** is updated to the latest version, **pip** is updated to the latest version, **openpyxl** is installed, **pytest** version is 3.3.1.

Will appreciate any suggestion,
Thanks in advance.

**Comment by ssrikanta** [comment]
@avrahamswissa Let me check that

**Comment by krogercustomer** [comment]
@avrahamswissa did you receive any update on this issue? I am getting the same error on mac.

**Comment by avrahamswissa** [comment]
@krogercustomer not yet.

**Comment by ssrikanta** [comment]
@avrahamswissa @krogercustomer Fix is on the way, will publish on pip very shortly.

**Comment by avrahamswissa** [comment]
@ssrikanta cheers!

**Comment by ssrikanta** [comment]
Fixed and published

**Comment by krogercustomer** [comment]
Thank you very much
