### ISSUE TITLE
Exception on report.longrepr.reprcrash is None

### ISSUE THREAD

**Issue by isanych** [ssrikanta/pytest-excel#35]
I'm getting pytest internal error on
```
E               File ".../python-3.10.4/lib/python3.10/site-packages/pytest_excel/pytest_excel.py", line 125, in append_failure
E                 message = report.longrepr.reprcrash.message
E             AttributeError: 'NoneType' object has no attribute 'message'
```
and when I'm adding `report.longrepr.reprcrash` not None check next exception happens on `unicode` non existing in python3. I'm using next patch which is good for python3:
```
@@ -118,16 +118,14 @@
 
         if hasattr(report, "wasxfail"):
             status = "XPASSED"
             message = "xfail-marked test passes Reason: %s " % report.wasxfail
 
         else:
-            if hasattr(report.longrepr, "reprcrash"):
+            if hasattr(report.longrepr, "reprcrash") and report.longrepr.reprcrash:
                 message = report.longrepr.reprcrash.message
-            elif isinstance(report.longrepr, (unicode, str)):
-                message = report.longrepr
             else:
                 message = str(report.longrepr)
 
             status = "FAILED"
 
         self.build_result(report, status, message)
```
python2 requires more work I guess

**Comment by istorrs** [comment]
I also get the "unicode" error using python3.8, pytest 7.1.2 and pytest-excel 1.5.0

`INFO     root:testpoint.py:234 testpoint:testpoint_runtest_makereport
************************************************************** [XPASS(strict)] JIRA-12345: Testing xfail
FAILED                                                                                                                                                                                                                      [ 55%]
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/jenkinsagent/.local/lib/python3.8/site-packages/_pytest/main.py", line 268, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/jenkinsagent/.local/lib/python3.8/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/jenkinsagent/.local/lib/python3.8/site-packages/_pytest/main.py", line 347, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/jenkinsagent/.local/lib/python3.8/site-packages/_pytest/runner.py", line 111, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/jenkinsagent/.local/lib/python3.8/site-packages/_pytest/runner.py", line 130, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/home/jenkinsagent/.local/lib/python3.8/site-packages/_pytest/runner.py", line 223, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/jenkinsagent/.local/lib/python3.8/site-packages/pytest_excel/pytest_excel.py", line 227, in pytest_runtest_logreport
INTERNALERROR>     self.append_failure(report)
INTERNALERROR>   File "/home/jenkinsagent/.local/lib/python3.8/site-packages/pytest_excel/pytest_excel.py", line 126, in append_failure
INTERNALERROR>     elif isinstance(report.longrepr, (unicode, str)):
INTERNALERROR> NameError: name 'unicode' is not defined

`
